data_path: 'dataset/office-arts/' # 游때
pq_data: OA # 游때
datasets: 'Office,Arts' #游때
benchmark_filename: [train, valid, test]
alias_of_item_id: [item_id_list]
load_col:
  inter: [user_id, item_id_list, item_id]
neg_sampling: ~
transform: ~

topk: [10, 50]
metrics: [Recall, NDCG]
valid_metric: Recall@10
stopping_step: 10
gpu_id : 5
learning_rate: 0.001
epoch: 100

save_step: 10
train_batch_size: 1024

index_path: dataset/office-arts #游때
index_pretrain_dataset: Office #游때
filter_id_suffix: filtered_id
filter_id_suffix_user: filtered_user_id
checkpoint_dir : 'save_OA/' #游때
